### ISSUE TITLE
Relationship links do not follow API spec (?)

### ISSUE THREAD

**Issue by OskarD** [nilportugues/api-transformer#8]
I started looking at the relationships in this project, and this is what they look like in the tests:

```
'relationships' => [
    'author' => [
        'related' => 'http://example.com/posts/{postId}/author',
        'self' => 'http://example.com/posts/{postId}/relationships/author',
    ],
],
```

But this is how they look in the JSON API specification:

```
"relationships"      => [
    "author" => [
        "links" => [
            "self"    => "/articles/1/relationships/author",
            "related" => "/articles/1/author",
        ],
    ],
],
```

I changed a test according to this model (`testItCanBuildMappingsFromArray`), and it doesn't pass.

```
1) NilPortugues\Tests\Api\Mapping\MappingFactoryTest::testItCanBuildMappingsFromArray
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'http://example.com/posts/{postId}/author'
+''
```

on this line:

```
       $this->assertEquals('http://example.com/posts/{postId}/author',
            $mapping->getRelatedUrl('author'));
```

Does this mean that the package is breaking spec?

**Comment by nilportugues** [comment]
I agree, there's a level missing. This is probably because I took the http://jsonapi.org/format/#document-links too literal and missed adding the `links` keyword as done in other examples.

A quick fix can be applied here. Problem is at https://github.com/nilportugues/php-json-api.

This package is not meant to be JSONAPI specific, but generic. So the issue is not here.

**Comment by OskarD** [comment]
So will it be changed in this package or should it stay the way it is? 

I can't find an example where a relationship contains an ID or an attribute, how will this be implemented?

**Comment by nilportugues** [comment]
@OskarD maybe this? https://github.com/nilportugues/php-json-api/blob/master/tests/JsonApiTransformerTest.php#L71

**Comment by OskarD** [comment]
I meant for this package :) Which project should I fix the pivot data issue in?

**Comment by OskarD** [comment]
@nilportugues I meant for this package :) Which project should I fix the pivot data issue in? https://github.com/nilportugues/laravel5-jsonapi/issues/63

**Comment by nilportugues** [comment]
@OskarD laravel5-jsonapi or https://github.com/nilportugues/serializer-eloquent-driver

**Comment by OskarD** [comment]
@nilportugues is there any chance you can take care of it? I have some time pressure right now and while this is blocking some of the progress, I have a lot more things to do as well. It would be highly appreciated :)

**Comment by nilportugues** [comment]
@OskarD will look into it :+1:
